### PR TITLE
feat: Added Product Page

### PR DESCRIPTION
**Pull request by vishal804**
Hello,

Created Product Page 
Please Review 

Thank You

### CODE REVIEW

**Comment by Vishnu-Aithal** [comment]
Looks Nice !
Buttons Borders are overflowing a bit on hover cards

image

**Review by hsnice16 — APPROVED** [review]
The code looks good. And, Nice work on UI.

**Review by Vishnu-Aithal — APPROVED** [review]

**Comment by vishal804** [comment]
> The code looks good. And, Nice work on UI.

Thank You

**Comment by vishal804** [comment]
> Looks Nice ! Buttons Borders are overflowing a bit on hover cards
> 
> image


Thanks For Pointing Out will fix that

**Pull request merged**
